# Generated by Django 4.2.11 on 2024-05-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/wine/"),
        ),
    ]
