# Generated by Django 4.2.11 on 2024-05-29 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_wine_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="parentRegion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.region",
            ),
        ),
    ]
